//! Static language metadata table.
//!
//! `LANGUAGES` is the single source of truth. Its order defines the numeric
//! [`crate::LanguageId`] values, so the `Language::*` constants in
//! [`crate::language`] must line up with it (enforced by tests).

use crate::category::LanguageCategory::{self, *};
use crate::comment::{BlockComment, CommentStyle};
use crate::language::Language;
use crate::meta::{Color, Icon};

/// All metadata describing a single language.
#[derive(Debug, Clone, Copy)]
pub struct LanguageInfo {
    pub language: Language,
    pub canonical_name: &'static str,
    pub display_name: &'static str,

    pub aliases: &'static [&'static str],
    pub extensions: &'static [&'static str],
    pub filenames: &'static [&'static str],
    pub shebangs: &'static [&'static str],

    pub comments: CommentStyle,
    pub category: LanguageCategory,
    pub color: Option<Color>,
    pub icon: Option<Icon>,
}

const fn line(prefixes: &'static [&'static str]) -> CommentStyle {
    CommentStyle::new(prefixes, &[])
}

const HASH: CommentStyle = line(&["#"]);
const SEMI: CommentStyle = line(&[";"]);
const C_LIKE: CommentStyle = CommentStyle::new(&["//"], &[BlockComment::new("/*", "*/")]);
const ANGLE_COMMENT: CommentStyle = CommentStyle::new(&[], &[BlockComment::new("<!--", "-->")]);
const BLOCK_ONLY: CommentStyle = CommentStyle::new(&[], &[BlockComment::new("/*", "*/")]);
const LUA_COMMENT: CommentStyle = CommentStyle::new(&["--"], &[BlockComment::new("--[[", "]]")]);
const SQL_COMMENT: CommentStyle = CommentStyle::new(&["--"], &[BlockComment::new("/*", "*/")]);
const PHP_COMMENT: CommentStyle = CommentStyle::new(&["//", "#"], &[BlockComment::new("/*", "*/")]);
const HASKELL_COMMENT: CommentStyle = CommentStyle::new(&["--"], &[BlockComment::new("{-", "-}")]);

/// The registry table. Index == [`crate::LanguageId`].
pub static LANGUAGES: &[LanguageInfo] = &[
    LanguageInfo {
        language: Language::from_index(0),
        canonical_name: "rust",
        display_name: "Rust",
        aliases: &["rust", "rs"],
        extensions: &["rs"],
        filenames: &[],
        shebangs: &[],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(222, 165, 132)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(1),
        canonical_name: "python",
        display_name: "Python",
        aliases: &["python", "python3", "py"],
        extensions: &["py", "pyi", "pyw"],
        filenames: &[],
        shebangs: &["python", "python2", "python3"],
        comments: HASH,
        category: Code,
        color: Some(Color::rgb(53, 114, 165)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(2),
        canonical_name: "makefile",
        display_name: "Makefile",
        aliases: &["makefile", "make"],
        extensions: &["mk", "mak"],
        filenames: &["Makefile", "makefile", "GNUmakefile"],
        shebangs: &[],
        comments: HASH,
        category: Build,
        color: Some(Color::rgb(66, 120, 25)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(3),
        canonical_name: "shell",
        display_name: "Shell",
        aliases: &["shell", "sh", "bash", "zsh"],
        extensions: &["sh", "bash", "zsh", "ksh"],
        filenames: &[".bashrc", ".bash_profile", ".zshrc", ".profile"],
        shebangs: &["sh", "bash", "zsh", "ksh", "dash"],
        comments: HASH,
        category: Code,
        color: Some(Color::rgb(137, 224, 81)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(4),
        canonical_name: "javascript",
        display_name: "JavaScript",
        aliases: &["javascript", "js", "node"],
        extensions: &["js", "mjs", "cjs"],
        filenames: &[],
        shebangs: &["node"],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(241, 224, 90)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(5),
        canonical_name: "ini",
        display_name: "INI",
        aliases: &["ini", "dosini"],
        extensions: &["ini", "desktop", "lfl", "override", "tscn", "tres"],
        filenames: &["mimeapps.list", "pinforc", "setup.cfg", "project.godot"],
        shebangs: &[],
        comments: SEMI,
        category: Config,
        color: None,
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(6),
        canonical_name: "gitconfig",
        display_name: "Git Config",
        aliases: &["gitconfig", "git-config"],
        extensions: &[],
        filenames: &["gitconfig", ".gitconfig", "gitmodules", ".gitmodules"],
        shebangs: &[],
        comments: line(&["#", ";"]),
        category: Config,
        color: None,
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(7),
        canonical_name: "git-rebase-todo",
        display_name: "Git Rebase Todo",
        aliases: &["git-rebase", "gitrebase"],
        extensions: &[],
        filenames: &["git-rebase-todo"],
        shebangs: &[],
        comments: HASH,
        category: Config,
        color: None,
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(8),
        canonical_name: "nginx",
        display_name: "Nginx",
        aliases: &["nginx"],
        extensions: &[],
        filenames: &["nginx.conf"],
        shebangs: &[],
        comments: HASH,
        category: Config,
        color: None,
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(9),
        canonical_name: "crontab",
        display_name: "Crontab",
        aliases: &["crontab", "cron"],
        extensions: &[],
        filenames: &["crontab"],
        shebangs: &[],
        comments: HASH,
        category: Config,
        color: None,
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(10),
        canonical_name: "mpd-config",
        display_name: "MPD Config",
        aliases: &["mpd"],
        extensions: &[],
        filenames: &["mpd.conf"],
        shebangs: &[],
        comments: HASH,
        category: Config,
        color: None,
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(11),
        canonical_name: "toml",
        display_name: "TOML",
        aliases: &["toml"],
        extensions: &["toml"],
        filenames: &["Cargo.lock"],
        shebangs: &[],
        comments: HASH,
        category: Config,
        color: None,
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(12),
        canonical_name: "json",
        display_name: "JSON",
        aliases: &["json", "jsonc"],
        extensions: &["json", "jsonc"],
        filenames: &[],
        shebangs: &[],
        comments: CommentStyle::NONE,
        category: Data,
        color: None,
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(13),
        canonical_name: "markdown",
        display_name: "Markdown",
        aliases: &["markdown", "md"],
        extensions: &["md", "markdown", "mdown", "mkd"],
        filenames: &["README"],
        shebangs: &[],
        comments: CommentStyle::NONE,
        category: Document,
        color: None,
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(14),
        canonical_name: "c",
        display_name: "C",
        aliases: &["c"],
        extensions: &["c", "h"],
        filenames: &[],
        shebangs: &[],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(85, 85, 85)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(15),
        canonical_name: "cpp",
        display_name: "C++",
        aliases: &["cpp", "c++", "cxx"],
        extensions: &["cpp", "cc", "cxx", "c++", "hpp", "hxx", "h++", "hh"],
        filenames: &[],
        shebangs: &[],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(243, 75, 125)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(16),
        canonical_name: "go",
        display_name: "Go",
        aliases: &["go", "golang"],
        extensions: &["go"],
        filenames: &[],
        shebangs: &[],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(0, 173, 216)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(17),
        canonical_name: "typescript",
        display_name: "TypeScript",
        aliases: &["typescript", "ts", "tsx"],
        extensions: &["ts", "tsx"],
        filenames: &[],
        shebangs: &["ts-node", "deno"],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(49, 120, 198)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(18),
        canonical_name: "html",
        display_name: "HTML",
        aliases: &["html", "htm"],
        extensions: &["html", "htm"],
        filenames: &[],
        shebangs: &[],
        comments: ANGLE_COMMENT,
        category: Markup,
        color: Some(Color::rgb(227, 76, 38)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(19),
        canonical_name: "css",
        display_name: "CSS",
        aliases: &["css"],
        extensions: &["css"],
        filenames: &[],
        shebangs: &[],
        comments: BLOCK_ONLY,
        category: Code,
        color: Some(Color::rgb(86, 61, 124)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(20),
        canonical_name: "yaml",
        display_name: "YAML",
        aliases: &["yaml", "yml"],
        extensions: &["yaml", "yml"],
        filenames: &[],
        shebangs: &[],
        comments: HASH,
        category: Config,
        color: Some(Color::rgb(203, 23, 30)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(21),
        canonical_name: "xml",
        display_name: "XML",
        aliases: &["xml"],
        extensions: &["xml"],
        filenames: &[],
        shebangs: &[],
        comments: ANGLE_COMMENT,
        category: Markup,
        color: Some(Color::rgb(0, 96, 172)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(22),
        canonical_name: "java",
        display_name: "Java",
        aliases: &["java"],
        extensions: &["java"],
        filenames: &[],
        shebangs: &[],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(176, 114, 25)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(23),
        canonical_name: "csharp",
        display_name: "C#",
        aliases: &["csharp", "c#", "cs"],
        extensions: &["cs"],
        filenames: &[],
        shebangs: &[],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(23, 134, 0)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(24),
        canonical_name: "ruby",
        display_name: "Ruby",
        aliases: &["ruby", "rb"],
        extensions: &["rb"],
        filenames: &[],
        shebangs: &["ruby"],
        comments: HASH,
        category: Code,
        color: Some(Color::rgb(112, 21, 22)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(25),
        canonical_name: "php",
        display_name: "PHP",
        aliases: &["php"],
        extensions: &["php"],
        filenames: &[],
        shebangs: &["php"],
        comments: PHP_COMMENT,
        category: Code,
        color: Some(Color::rgb(79, 93, 149)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(26),
        canonical_name: "lua",
        display_name: "Lua",
        aliases: &["lua"],
        extensions: &["lua"],
        filenames: &[],
        shebangs: &["lua"],
        comments: LUA_COMMENT,
        category: Code,
        color: Some(Color::rgb(0, 0, 128)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(27),
        canonical_name: "sql",
        display_name: "SQL",
        aliases: &["sql"],
        extensions: &["sql"],
        filenames: &[],
        shebangs: &[],
        comments: SQL_COMMENT,
        category: Code,
        color: Some(Color::rgb(227, 140, 0)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(28),
        canonical_name: "dockerfile",
        display_name: "Dockerfile",
        aliases: &["dockerfile", "docker"],
        extensions: &["dockerfile"],
        filenames: &["Dockerfile", "dockerfile", "Containerfile"],
        shebangs: &[],
        comments: HASH,
        category: Build,
        color: Some(Color::rgb(56, 77, 84)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(29),
        canonical_name: "zig",
        display_name: "Zig",
        aliases: &["zig"],
        extensions: &["zig"],
        filenames: &[],
        shebangs: &[],
        comments: line(&["//"]),
        category: Code,
        color: Some(Color::rgb(236, 145, 92)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(30),
        canonical_name: "oxygen",
        display_name: "Oxygen",
        aliases: &["oxygen", "oxy"],
        extensions: &["oxy"],
        filenames: &[],
        shebangs: &[],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(0, 180, 216)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(31),
        canonical_name: "verilog",
        display_name: "Verilog",
        aliases: &["verilog", "v"],
        extensions: &["v", "vh"],
        filenames: &[],
        shebangs: &[],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(178, 183, 248)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(32),
        canonical_name: "systemverilog",
        display_name: "SystemVerilog",
        aliases: &["systemverilog", "sv"],
        extensions: &["sv", "svh"],
        filenames: &[],
        shebangs: &[],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(218, 225, 194)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(33),
        canonical_name: "vhdl",
        display_name: "VHDL",
        aliases: &["vhdl"],
        extensions: &["vhd", "vhdl"],
        filenames: &[],
        shebangs: &[],
        comments: line(&["--"]),
        category: Code,
        color: Some(Color::rgb(173, 178, 203)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(34),
        canonical_name: "bsv",
        display_name: "Bluespec SystemVerilog",
        aliases: &["bsv", "bluespec-systemverilog"],
        extensions: &["bsv"],
        filenames: &[],
        shebangs: &[],
        comments: C_LIKE,
        category: Code,
        color: Some(Color::rgb(18, 34, 60)),
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(35),
        canonical_name: "bh",
        display_name: "Bluespec Haskell",
        aliases: &["bh", "bluespec-haskell"],
        extensions: &["bs"],
        filenames: &[],
        shebangs: &[],
        comments: HASKELL_COMMENT,
        category: Code,
        color: None,
        icon: None,
    },
    LanguageInfo {
        language: Language::from_index(36),
        canonical_name: "sdc",
        display_name: "SDC/XDC",
        aliases: &["sdc", "xdc"],
        extensions: &["sdc", "xdc"],
        filenames: &[],
        shebangs: &[],
        comments: HASH,
        category: Config,
        color: None,
        icon: None,
    },
];
